apiVersion: apps/v1
kind: Deployment
metadata:
  name: static
  namespace: default
  labels:
    app: static
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static
  template:
    metadata:
      labels:
        app: static
    spec:
      containers:
        - name: static
          image: zedtux/docker-coming-soon:latest
          ports:
            - name: http
              containerPort: 80
          env:
            - name: TITLE
              value: "StackBox DC"
            - name: PRODUCT_NAME
              value: "StackBox DC"
            - name: CATCHY_PHRASE
              value: " "
---
apiVersion: v1
kind: Service
metadata:
  name: static
  namespace: default
spec:
  selector:
    app: static
  ports:
    - protocol: TCP
      port: 80
      targetPort: http